### PR TITLE
Fix Linux-only 3.1 regex issue

### PR DESCRIPTION
**Pull request by carlbrown**

### CODE REVIEW

**Comment by ianpartridge** [comment]
Why can't we just specify that Kitura 1.next requires Swift 3.1, get rid of the `typealias` entirely, and use `NSRegularExpression` everywhere?

**Comment by carlbrown** [comment]
@ianpartridge  I think we will get rid of the type alias at some point, but let's be honest - we do a poor job of helping people manage the transition between swift/Xcode versions. If a few lines of code means that our users can upgrade at their leisure instead of on our schedule, isn't that a much better development experience?

**Comment by carlbrown** [comment]
This PR (and others like it) would also reduce the urgency for us to release the new tag the moment that Xcode 8.3 is released.

**Comment by ianpartridge** [comment]
If there's nothing else in the release that requires Swift 3.1 and you are not going to tell Kitura users to use Swift 3.1 then fine, but if you are going to mandate Swift 3.1 then I would take the opportunity to remove the `typealias` entirely.

**Comment by ianpartridge** [comment]
Previously we have said "use version X of Swift with Kitura Y". If the plan is to decouple then that's fine, but it complicates Kitura testing.

**Comment by carlbrown** [comment]
I realize this complicates testing.  If there were more structural changes, then I'd be more hesitant, but given the emphasis on source compatibility in Swift 3.1, this is (in my opinion) is a simple enough change that I'm not worried about it (which may fall into the category of "famous last words").

**Pull request merged**
